### ISSUE TITLE
implementation for aten::max.dim_max

### ISSUE THREAD

**Issue by eazy-f** [artyom-beilis/pytorch_dlprim#29]
Ran into missing implementation issue with `resnet34` training. The same code runs on CPU and CUDA without a problem.

* torch version: 2.1.0.dev20230321+cpu
* torchvision version: 0.16.0.dev20230321+cpu

Also noticed that `aten::_copy_from_and_resize` is missing, but I suppose a separate issue is required.

*update*: to be fair the functions isn't used by the resnet34 training itself, but by `torch.max` function called alongside. Having all auxiliary operations moved to CPU paved the way to successful training, though the GPU utilization seemed a bit low being around 30%.

**Comment by artyom-beilis** [comment]
Interesting... I didn't seen it. I'm going to check. Probably new functionality.

**Comment by artyom-beilis** [comment]
`_copy_and_resize` fixed so if something does not work feel free to reopen
