### ISSUE TITLE
variable of "or" in pooling.cl

### ISSUE THREAD

**Issue by smilealvin92** [artyom-beilis/pytorch_dlprim#42]
in some version OpenCL driver or compiler, the word of "or" is a key word of languages. So the compilation of this kernel may fail due to the variable name in pooling.cl. just change it to whatever you like, and the compilation will be smoothily

**Comment by artyom-beilis** [comment]
Fixed in d420ce6a609db458e81d600e7d3f0b9c1454edfb

I fixed some time ago it but forgot to update the pointer to dlprimitives backend. (i.e. submodule)
