### ISSUE TITLE
A question about Benchmark

### ISSUE THREAD

**Issue by ggangliu** [artyom-beilis/pytorch_dlprim#57]
I have a question in reading section "Full Train" and "Test", what is "pytorch/opencl",  dose it means using pytorch_dlprim repo or other?

**Comment by artyom-beilis** [comment]
> I have a question in reading section "Full Train" and "Test", what is "pytorch/opencl", dose it means using pytorch_dlprim repo or other?

Yes, pytorch/opencl is using `pytorch_dlprim` - backend for pytorch.

**Comment by ggangliu** [comment]
> > I have a question in reading section "Full Train" and "Test", what is "pytorch/opencl", dose it means using pytorch_dlprim repo or other?
> 
> Yes, pytorch/opencl is using `pytorch_dlprim` - backend for pytorch.

Thanks
