### ISSUE TITLE
clamp and clamp_min need to use self_c for X instead of self

### ISSUE THREAD

**Issue by artyom-beilis** [artyom-beilis/pytorch_dlprim#62]

**Comment by sukamenev** [comment]
What's the difference between self and self_c?

**Comment by artyom-beilis** [comment]
dlprimitives work only on contiguous tensors, if input isn't contiguous it is converted to one by calling

    Tensor self_c = self.contiguous();

`self_c` is promised to be contiguous, so `self_c` should be used. It is a bug in my original code, I noticed it when I reviewed the code.

**Comment by sukamenev** [comment]
I fixed these and other errors in my pull request.

But the following line in my code confuses me. Will it cause a memory leak?

`self = self.contigouos()`

It seems that in modern C++ this should not cause problems. But I would like to hear your opinion as an expert.

**Comment by artyom-beilis** [comment]
self = self.contigouos() 

Is incorrect indeed.

I'll describe in more details in pool request

**Comment by artyom-beilis** [comment]
Fixed in the pull
