### ISSUE TITLE
Benchmark script do not run. 'tools' dir is absent.

### ISSUE THREAD

**Issue by sukamenev** [artyom-beilis/pytorch_dlprim#68]
. ./benchark_all.sh .
python: can't open file '/home/inetstar/Kamenev/programming/ZenDnn/pytorch_dlprim/./tools/validate_network.py': [Errno 2] No such file or directory
alexnet
python: can't open file '/home/inetstar/Kamenev/programming/ZenDnn/pytorch_dlprim/./tools/validate_network.py': [Errno 2] No such file or directory
resnet18
python: can't open file '/home/inetstar/Kamenev/programming/ZenDnn/pytorch_dlprim/./tools/validate_network.py': [Errno 2] No such file or directory
vgg16
python: can't open file '/home/inetstar/Kamenev/programming/ZenDnn/pytorch_dlprim/./tools/validate_network.py': [Errno 2] No such file or directory
densenet161
python: can't open file '/home/inetstar/Kamenev/programming/ZenDnn/pytorch_dlprim/./tools/validate_network.py': [Errno 2] No such file or directory
inception_v3
python: can't open file '/home/inetstar/Kamenev/programming/ZenDnn/pytorch_dlprim/./tools/validate_network.py': [Errno 2] No such file or directory
mobilenet_v2
python: can't open file '/home/inetstar/Kamenev/programming/ZenDnn/pytorch_dlprim/./tools/validate_network.py': [Errno 2] No such file or directory
mobilenet_v3_small
python: can't open file '/home/inetstar/Kamenev/programming/ZenDnn/pytorch_dlprim/./tools/validate_network.py': [Errno 2] No such file or directory
mobilenet_v3_large
python: can't open file '/home/inetstar/Kamenev/programming/ZenDnn/pytorch_dlprim/./tools/validate_network.py': [Errno 2] No such file or directory
resnext50_32x4d
python: can't open file '/home/inetstar/Kamenev/programming/ZenDnn/pytorch_dlprim/./tools/validate_network.py': [Errno 2] No such file or directory
wide_resnet50_2
python: can't open file '/home/inetstar/Kamenev/programming/ZenDnn/pytorch_dlprim/./tools/validate_network.py': [Errno 2] No such file or directory
mnasnet1_0
python: can't open file '/home/inetstar/Kamenev/programming/ZenDnn/pytorch_dlprim/./tools/validate_network.py': [Errno 2] No such file or directory
efficientnet_b0
python: can't open file '/home/inetstar/Kamenev/programming/ZenDnn/pytorch_dlprim/./tools/validate_network.py': [Errno 2] No such file or directory
efficientnet_b4
python: can't open file '/home/inetstar/Kamenev/programming/ZenDnn/pytorch_dlprim/./tools/validate_network.py': [Errno 2] No such file or directory
regnet_y_400mf

**Comment by artyom-beilis** [comment]
You need to run 

    bash benchark_all.sh dlprimitives/

Should have better docs

**Comment by artyom-beilis** [comment]
Fixed in b8a7061cbdd31db04dc7843156f0fc4af2eb6893
