### ISSUE TITLE
Error in "pytorch_ocl". Make error

### ISSUE THREAD

**Issue by sukamenev** [artyom-beilis/pytorch_dlprim#80]
I added line "import pytorch_ocl" to test.py

python test.py 
Traceback (most recent call last):
  File "/home/.../pytorch_dlprim/test.py", line 4, in <module>
    import pytorch_ocl
  File "/home/.../programming/lib/python3.11/site-packages/pytorch_ocl/__init__.py", line 2, in <module>
    from .pt_ocl import *
ImportError: Python version mismatch: module was compiled for Python 3.12, but the interpreter version is incompatible: 3.11.8 (main, Feb 26 2024, 13:06:38) [GCC 13.2.1 20240113].

By building:

OpenCL: include /usr/include
          lib     /usr/lib64/libOpenCL.so
  Python: /home/.../bin/python3
  BLAS: None
  HDF5: None
  Sqlite3: include /usr/include
           lib /usr/lib64/libsqlite3.so
  Protobuf (onnx): disabled
  Python dlprim: disabled
  Pytorch libraries torch;torch_library;/home/.../lib/python3.11/site-packages/torch/lib/libc10.so
  Python libraries /usr/lib64/libpython3.12.so
  
  I see error: by configuring I set python 3.11, but by making was used system python 3.12

**Comment by artyom-beilis** [comment]
Thee is probably a build error: ImportError: Python version mismatch: module was compiled for Python 3.12, but the interpreter version is incompatible

Likely you had include to wrong python version if python installation is non standard use `-DPYTHON_INCLUDE_DIR` and `-`-DPYTHON_LIBRARY` pointing to location of header file and actual libpython3.x.so/a
